### PR TITLE
black twitter icon in nav bar

### PR DESCRIPTION
**Pull request by story645**
I think it could look more cohesive in black. I also think black is supposed to be the default so not clear why it's in blue.

### CODE REVIEW

**Comment by QuLogic** [comment]
Does it work for you? I tried this locally with the Inspector, and it didn't seem to have any affect.

This _does_ appear to be what the FontAwesome docs do on their example site though. Perhaps we have an older version of FontAwesome?

**Comment by story645** [comment]
I wasn't sure how to test honestly & I'm also wondering if it's a version thing cause the default icons are black

**Comment by QuLogic** [comment]
There's a build in the CI here you can check.

**Comment by story645** [comment]
So figured out builds #28 (thanks!) and yes the fab prefix is for v5 of font awesome https://fontawesome.com/v5/icons/twitter-square?s=brands

**Review by QuLogic — APPROVED** [review]
LGTM

**Pull request merged**
