### PR TITLE
FIX: do not explicitly import pydata theme

### PR DESCRIPTION
**Pull request by jklymak**
its already imported by sphinx.

### CODE REVIEW

**Comment by QuLogic** [comment]
Can we maybe tag a release with this? I keep seeing this 404 in the console log.

**Comment by jklymak** [comment]
@QuLogic, yes we should talk about how to tag this and mpl-brochure-site.  I am not sure how doc builds work once a release has been made.  

The released version of this probably needs to track the MPL doc release because the top menubar navigation is hard-coded here.  So dependent sites should use the stable version of the site, not the dev version.  This adds to the release burden because this needs to be checked and tagged at that point.  Then we shouldn't release again until the next docs release?

**Comment by QuLogic** [comment]
> @QuLogic, yes we should talk about how to tag this and mpl-brochure-site. I am not sure how doc builds work once a release has been made.
> 

The `mpl-brochure-site` is published from every commit on `main`, so we just need to push something there.

> The released version of this probably needs to track the MPL doc release because the top menubar navigation is hard-coded here. So dependent sites should use the stable version of the site, not the dev version. This adds to the release burden because this needs to be checked and tagged at that point. Then we shouldn't release again until the next docs release?

Doesn't it all link to /stable? Why do we need to coordinate releases?

**Comment by jklymak** [comment]
> The `mpl-brochure-site` is published from every commit on `main`, so we just need to push something there.

OK, that seems fine...

> 
> > The released version of this probably needs to track the MPL doc release because the top menubar navigation is hard-coded here. So dependent sites should use the stable version of the site, not the dev version. This adds to the release burden because this needs to be checked and tagged at that point. Then we shouldn't release again until the next docs release?
> 
> Doesn't it all link to /stable? Why do we need to coordinate releases?

The brochure site indeed always points to stable, as do the satelite sites.  

If we use mpl_sphinx-theme  on the main site, it will use relative links.  So when it is built, matplotlib.org/3.5.0/docs/index.html  the tutorial link _should_ point to  matplotlib.org/3.5.0/tutorials.  Which is all fine, if we never rebuild the docs.  However, lets say we decide to change the top-level nav and there is a link to 3.6.0/future-cool-thing and we rebuild the 3.5 docs, they will get that button and it will point to non-existent 3.5.0/future-cool-thing.  So if we ever want to rebuild the docs, we will need to install an old version of mpl-sphinx-theme to have the right nav - hence it probably is good to tag?

**Comment by jklymak** [comment]
See https://github.com/matplotlib/mpl-sphinx-theme/blob/main/mpl_sphinx_theme/mpl_nav_bar.html for the if-statment here...

**Comment by QuLogic** [comment]
Ah, we don't need to tie releases together all the time then. We should pin the theme version in Matplotlib, and release this one when it gets new stuff, then bump the theme in Matplotlib `main`.

**Comment by jklymak** [comment]
I think that would be fine.  But for sanity sake, maybe this should get the same version tags as Matplotlib so its easy to cross-correlate when the change went in?  i.e. we could stay on 3.5.0 until a change is made in 3.7.0 and then update the tag to 3.7.0 at that time?

**Comment by QuLogic** [comment]
Can you upload a new version now? We don't have parallel safeness, nor the fixed JS here.

**Comment by jklymak** [comment]
@QuLogic moved to gitter for clarification!

**Pull request merged**
